export default Object.freeze({
  LISTING_DETAILS: "ListingDetails",
  IMAGE_DETAILS: "ImageDetails",
  LISTING_EDIT: "ListingEdit",
  LISTING_ADD: "ListingAdd",
  USER_EDIT: "UserEdit",
  SETTINGS: "Settings",
  NOTIFICATIONS: "Notifications",
  LOGIN: "Login",
  REGISTER: "Register",
  FORGOT_PASSWORD: "ForgotPassword",
  RESET_PASSWORD: "ResetPassword",
  VERIFY_EMAIL: "VerifyEmail",
  ORDERS: "Orders",
  ORDER_DETAILS: "OrderDetails",
  ORDER_CHECKOUT: "OrderCheckout",
  Favorites: "Favorites",
  HELP: "HelpSupport",
  PRIVACY: "PrivacySecurity",
  SHIPPING_ADDRESSES: "ShippingAddresses",
  ACCOUNT: "Account",
  LISTINGS: "Listings",
  MY_LISTINGS: "MyListings",
  ALL_LISTINGS: "AllListings",
  CONVERSATION: "Conversation",
});
